<?php

declare(strict_types=1);

/** Renders the signed-in ArchiveXP Collection HQ. */

$escape=static fn(string $value): string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');
$themeStyle="--accent:{$currentUser->themeAccent()};--bg:{$currentUser->themeBackground()};--panel:{$currentUser->themePanel()};--text:{$currentUser->themeText()};";
$largest=$overview['largestFranchise'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection HQ — ArchiveXP</title><link rel="stylesheet" href="/assets/app.css"></head>
<body class="theme-<?= $escape($currentUser->themePreset()) ?> density-<?= $escape($currentUser->layoutDensity()) ?> <?= $currentUser->dashboardImage()!==null?'has-dashboard-image image-mode-'.$escape($currentUser->dashboardImageMode()):'' ?>" style="<?= $escape($themeStyle) ?><?= $currentUser->dashboardImage()!==null?'--dashboard-image:url(\'/?route=dashboard-image\');--dashboard-overlay:'.($currentUser->dashboardOverlay()/100):'' ?>">
<header class="site-header dashboard-header hq-hero"><div><p class="eyebrow">Welcome back, <?= $escape($currentUser->profileDisplayName()) ?></p><h1>Collection HQ</h1><p class="lede">Your games, collectibles, franchises, and next adventures—all in one place.</p></div><div class="summary"><strong><?= $overview['gameCounts']['all']+$overview['merchandiseCount'] ?></strong><span>items tracked</span></div></header>
<div class="account-bar"><div class="account-identity"><?php if($currentUser->profileImage()!==null): ?><img class="account-avatar account-avatar-image" src="/?route=profile-image&amp;user=<?= rawurlencode($currentUser->username()??'') ?>" alt=""><?php else: ?><span class="account-avatar"><?= $escape(strtoupper(substr($currentUser->displayName(),0,1))) ?></span><?php endif; ?><span><small>Signed in as</small><strong><?= $escape($currentUser->displayName()) ?></strong></span></div><a class="account-button" href="/?route=account">My Account</a><a class="account-button" href="/?route=appearance">Appearance</a><a class="account-button" href="/?route=profile-settings">Public profile</a><form method="post" action="/?route=logout"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><button class="logout-button">Sign out</button></form></div>
<nav class="section-switcher"><a class="is-active" href="/">Home</a><a href="/?route=games">Games</a><a href="/?route=merchandise">Merchandise</a><a href="/?route=franchises">Franchises</a></nav>
<main class="hq-layout">
<section class="hq-stats"><article><span>Games</span><strong><?= $overview['gameCounts']['all'] ?></strong><small><?= $overview['gameCounts']['completed'] ?> completed</small></article><article><span>Collectibles</span><strong><?= $overview['merchandiseCount'] ?></strong><small>owned items</small></article><article><span>Franchises</span><strong><?= $overview['franchiseCount'] ?></strong><small>connected worlds</small></article><article><span>Wishlist</span><strong><?= $overview['wishlistCount'] ?></strong><small>items wanted</small></article></section>
<section class="hq-portals"><a href="/?route=games"><p class="eyebrow">Play library</p><h2>Games</h2><p>Track platforms, progress, journals, ratings, and trophies.</p><span>Open games →</span></a><a href="/?route=merchandise"><p class="eyebrow">Display cabinet</p><h2>Merchandise</h2><p>Catalogue figures, statues, LEGO, packaging, and locations.</p><span>Open merchandise →</span></a><a href="/?route=franchises"><p class="eyebrow">Connected collection</p><h2>Franchise Atlas</h2><p>See games, characters, platforms, and collectibles together.</p><span>Explore franchises →</span></a></section>
<section class="hq-content"><div class="panel"><div class="panel-heading"><div><p class="eyebrow">Pick up where you left off</p><h2>Continue playing</h2></div><a class="text-link" href="/?route=games&amp;view=playing">View all</a></div><div class="hq-playing"><?php foreach($overview['playing'] as $game): ?><a href="/?route=game&amp;id=<?= $game->id() ?>"><strong><?= $escape($game->title()) ?></strong><small><?= $escape($game->platform()) ?></small><div class="progress-heading"><span>Progress</span><b><?= $game->progress() ?>%</b></div><div class="progress-track"><span style="width:<?= $game->progress() ?>%"></span></div></a><?php endforeach; ?><?php if($overview['playing']===[]): ?><div class="hq-empty"><span>▶</span><p>No active playthroughs yet.</p><a href="/?route=games">Choose a game</a></div><?php endif; ?></div></div>
<aside class="panel hq-insights"><p class="eyebrow">Collection pulse</p><h2>At a glance</h2><dl><div><dt>Game completion</dt><dd><?= $overview['completionRate'] ?>%</dd></div><div><dt>Favourite platform</dt><dd><?= $escape($overview['favouritePlatform']??'Not set') ?></dd></div><div><dt>Largest franchise</dt><dd><?= $largest===null?'Not set':$escape($largest['name']) ?></dd></div></dl><?php if($largest!==null): ?><a class="account-button" href="/?<?= $escape(http_build_query(['route'=>'franchise','name'=>$largest['name']])) ?>">View largest franchise</a><?php endif; ?></aside></section>
<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Latest arrivals</p><h2>Recently added</h2></div></div><div class="hq-recent"><div><h3>Games</h3><?php foreach($overview['recentGames'] as $game): ?><a href="/?route=game&amp;id=<?= $game->id() ?>"><span><?= $escape($game->title()) ?></span><small><?= $escape($game->platform()) ?></small></a><?php endforeach; ?></div><div><h3>Merchandise</h3><?php foreach($overview['recentMerchandise'] as $item): ?><a href="/?route=collection-details&amp;type=merchandise&amp;id=<?= $item->id() ?>"><span><?= $escape($item->name()) ?></span><small><?= $escape($item->category()->label()) ?></small></a><?php endforeach; ?></div></div></section>
<section class="hq-quick"><div><p class="eyebrow">Quick actions</p><h2>Grow your archive</h2></div><nav><a href="/?route=games#add-game">＋ Add game</a><a href="/?route=merchandise#add-merchandise">＋ Add merchandise</a><a href="/?route=data-transfer">⇄ Import or export CSV</a></nav></section>
</main></body></html>
