<?php

declare(strict_types=1);

/** Renders theme, density, and collection-artwork customisation. */

$escape=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');
$themeStyle="--accent:{$user->themeAccent()};--bg:{$user->themeBackground()};--panel:{$user->themePanel()};--text:{$user->themeText()}";
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Appearance — ArchiveXP</title><link rel="stylesheet" href="/assets/app.css"><script src="/assets/appearance.js" defer></script></head>
<body class="theme-<?= $escape($user->themePreset()) ?> density-<?= $escape($user->layoutDensity()) ?>" style="<?= $escape($themeStyle) ?>">
<header class="site-header account-header"><div><a class="back-link" href="/">← Back to collection</a><p class="eyebrow">Player settings</p><h1>Appearance</h1><p class="lede">Make ArchiveXP feel like your own collection room.</p></div></header>
<nav class="section-switcher settings-switcher"><a href="/?route=account">My Account</a><a class="is-active" href="/?route=appearance">Appearance</a></nav>
<main class="appearance-layout">
<?php if ($errors!==[]): ?><div class="alert alert-error appearance-message"><?php foreach($errors as $error): ?><p><?= $escape($error) ?></p><?php endforeach; ?></div><?php endif; ?><?php if($saved!==''): ?><div class="alert alert-success appearance-message">Appearance updated.</div><?php endif; ?>
<section class="panel theme-panel"><div class="panel-heading"><div><p class="eyebrow">Theme studio</p><h2>Colours and layout</h2></div><p class="section-description">Presets are ready to use, or choose custom colours with accessible contrast.</p></div>
<div class="theme-editor"><div class="theme-preview" data-theme-preview><div class="preview-header"><span>ArchiveXP</span><button type="button">Add game</button></div><div class="preview-cards"><article><strong>Collection card</strong><small>Your games</small></article><article><strong>Progress</strong><small>75% complete</small></article></div></div>
<form class="game-form" method="post" action="/?route=appearance" data-theme-form><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="section" value="theme">
<fieldset class="preset-grid"><legend>Theme preset</legend><?php foreach($presets as $key=>$preset): ?><label class="preset-option" style="--swatch-accent:<?= $preset['accent'] ?>;--swatch-bg:<?= $preset['background'] ?>"><input type="radio" name="theme_preset" value="<?= $key ?>" <?= $user->themePreset()===$key?'checked':'' ?> data-preset='<?= $escape(json_encode($preset,JSON_THROW_ON_ERROR)) ?>'><span><i></i><?= $escape($preset['label']) ?></span></label><?php endforeach; ?><label class="preset-option"><input type="radio" name="theme_preset" value="custom" <?= $user->themePreset()==='custom'?'checked':'' ?>><span><i class="custom-swatch"></i>Custom</span></label></fieldset>
<div class="colour-grid"><label><span>Accent</span><input type="color" name="theme_accent" value="<?= $escape($user->themeAccent()) ?>"></label><label><span>Background</span><input type="color" name="theme_background" value="<?= $escape($user->themeBackground()) ?>"></label><label><span>Panels</span><input type="color" name="theme_panel" value="<?= $escape($user->themePanel()) ?>"></label><label><span>Text</span><input type="color" name="theme_text" value="<?= $escape($user->themeText()) ?>"></label></div>
<label><span>Card spacing</span><select name="layout_density"><option value="spacious" <?= $user->layoutDensity()==='spacious'?'selected':'' ?>>Spacious</option><option value="compact" <?= $user->layoutDensity()==='compact'?'selected':'' ?>>Compact</option></select></label><p class="contrast-status" data-contrast-status>Checking colour contrast…</p><div class="appearance-actions"><button class="primary-button" type="submit">Save theme</button><button class="danger-button" type="submit" name="theme_action" value="reset">Reset defaults</button></div></form></div></section>
<?php foreach([['dashboard-artwork','Game dashboard','dashboard_image',$user->dashboardImage(),$user->dashboardImageMode(),$user->dashboardOverlay(),'dashboard-image'],['merchandise-artwork','Merchandise dashboard','merchandise_image',$user->merchandiseImage(),$user->merchandiseImageMode(),$user->merchandiseOverlay(),'merchandise-image']] as [$sectionKey,$title,$field,$image,$mode,$overlay,$imageRoute]): ?>
<section class="panel appearance-panel"><div class="panel-heading"><div><p class="eyebrow">Banner and wallpaper</p><h2><?= $title ?></h2></div></div><div class="appearance-grid"><div class="appearance-preview <?= $image===null?'is-empty':'' ?>" <?= $image!==null?'style="--dashboard-image:url(\'/?route='.$imageRoute.'\');--dashboard-overlay:'.($overlay/100).'"':'' ?>><?php if($image===null): ?><span>Your image preview will appear here</span><?php endif; ?></div><form method="post" action="/?route=appearance" class="game-form appearance-form" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="section" value="<?= $sectionKey ?>"><label><span>Choose an image</span><input type="file" name="<?= $field ?>" accept="image/jpeg,image/png,image/webp"></label><p class="field-help">JPEG, PNG, or WebP, up to 5 MB.</p><label><span>Display style</span><select name="image_mode"><option value="banner" <?= $mode==='banner'?'selected':'' ?>>Header banner</option><option value="wallpaper" <?= $mode==='wallpaper'?'selected':'' ?>>Page wallpaper</option></select></label><label><span>Dark overlay: <output><?= $overlay ?>%</output></span><input type="range" name="overlay" min="20" max="90" value="<?= $overlay ?>" oninput="this.previousElementSibling.querySelector('output').value=this.value+'%'"></label><div class="appearance-actions"><button class="primary-button" type="submit">Save artwork</button><?php if($image!==null): ?><button class="danger-button" type="submit" name="appearance_action" value="remove">Remove image</button><?php endif; ?></div></form></div></section><?php endforeach; ?>
</main></body></html>
