<?php

declare(strict_types=1);

/** Renders private or shareable franchise collection details. */

$escape=static fn(string $value): string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');$themeStyle="--accent:{$currentUser->themeAccent()};--bg:{$currentUser->themeBackground()};--panel:{$currentUser->themePanel()};--text:{$currentUser->themeText()};";
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $franchise===null?'Franchise unavailable':$escape($franchise['name']) ?> — ArchiveXP</title><link rel="stylesheet" href="/assets/app.css"></head><body class="theme-<?= $escape($currentUser->themePreset()) ?> density-<?= $escape($currentUser->layoutDensity()) ?> <?= !$isPublic&&$currentUser->franchiseImage()!==null?'has-dashboard-image image-mode-'.$escape($currentUser->franchiseImageMode()):'' ?>" style="<?= $escape($themeStyle) ?><?= !$isPublic&&$currentUser->franchiseImage()!==null?'--dashboard-image:url(\'/?route=franchise-image\');--dashboard-overlay:'.($currentUser->franchiseOverlay()/100):'' ?>">
<?php if($franchise===null): ?><main class="public-empty"><p class="eyebrow">ArchiveXP</p><h1>Franchise unavailable</h1><p>This collection is private or does not exist.</p></main><?php return;endif; ?>
<header class="site-header franchise-hero"><div><a class="back-link" href="<?= $isPublic?'/?route=display-cabinet&user='.rawurlencode($currentUser->username()??''):'/?route=franchises' ?>">← <?= $isPublic?'Back to cabinet':'All franchises' ?></a><p class="eyebrow"><?= $isPublic?'Shared franchise collection':'Franchise Collection Atlas' ?></p><h1><?= $escape($franchise['name']) ?></h1><p class="lede"><?= count($franchise['games']) ?> games, <?= count($franchise['merchandise']) ?> collectibles, and <?= count($franchise['characters']) ?> represented characters.</p></div><div class="summary"><strong><?= $franchise['total'] ?></strong><span>items</span></div></header>
<section class="franchise-stats"><article><strong><?= $franchise['completed'] ?></strong><span>Games completed</span></article><article><strong><?= count($franchise['platforms']) ?></strong><span>Platforms</span></article><article><strong><?= count($franchise['characters']) ?></strong><span>Characters</span></article><article><strong><?= count($franchise['wishlistGames'])+count($franchise['wishlistMerchandise']) ?></strong><span>Wanted</span></article></section>
<?php if(!$isPublic): ?><nav class="franchise-actions"><a class="account-button" href="/?route=franchises">Franchise Atlas</a><?php if($currentUser->profilePublic()): ?><a class="account-button" href="/?<?= $escape(http_build_query(['route'=>'public-franchise','user'=>$currentUser->username(),'name'=>$franchise['name']])) ?>">View public page</a><?php endif; ?></nav><?php endif; ?>
<main class="franchise-layout"><div class="franchise-main"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">Play history</p><h2>Games</h2></div></div><div class="franchise-item-grid"><?php foreach($franchise['games'] as $game): ?><article><span class="status-pill"><?= $escape($game->collectionType()->value) ?></span><h3><?= $escape($game->title()) ?></h3><p><?= $escape($game->platform()) ?></p><div class="progress-heading"><span>Progress</span><strong><?= $game->progress() ?>%</strong></div><div class="progress-track"><span style="width:<?= $game->progress() ?>%"></span></div></article><?php endforeach; ?><?php if($franchise['games']===[]): ?><p class="empty-state">No games connected yet.</p><?php endif; ?></div></section>
<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Physical archive</p><h2>Merchandise</h2></div></div><div class="franchise-item-grid"><?php foreach($franchise['merchandise'] as $item): ?><article><span class="status-pill"><?= $escape($item->collectionType()->value) ?></span><h3><?= $escape($item->name()) ?></h3><p><?= $escape($item->category()->label()) ?> · <?= $escape($item->packaging()->label()) ?></p></article><?php endforeach; ?><?php if($franchise['merchandise']===[]): ?><p class="empty-state">No merchandise connected yet.</p><?php endif; ?></div></section></div>
<aside class="franchise-sidebar"><section class="panel"><p class="eyebrow">Collection coverage</p><h2>Characters</h2><div class="character-cloud"><?php foreach($franchise['characters'] as $character): ?><span><?= $escape($character) ?></span><?php endforeach; ?><?php if($franchise['characters']===[]): ?><p class="field-help">Add character tags in Collection details.</p><?php endif; ?></div><h3>Platforms</h3><div class="character-cloud"><?php foreach($franchise['platforms'] as $platform): ?><span><?= $escape($platform) ?></span><?php endforeach; ?></div></section>
<section class="panel"><p class="eyebrow">Goals</p><h2>Collection quests</h2><?php foreach($franchise['goals'] as $goalData): ?><article class="goal-card"><div><strong><?= $escape($goalData['goal']->title()) ?></strong><small><?= $goalData['current'] ?> / <?= $goalData['goal']->targetCount() ?> <?= $escape($goalData['goal']->itemType()) ?></small></div><div class="progress-track"><span style="width:<?= $goalData['percentage'] ?>%"></span></div><?php if(!$isPublic): ?><form method="post" action="/?<?= $escape(http_build_query(['route'=>'franchise','name'=>$franchise['name']])) ?>"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="goal_action" value="delete"><input type="hidden" name="goal_id" value="<?= $goalData['goal']->id() ?>"><button class="text-link">Remove</button></form><?php endif; ?></article><?php endforeach; ?><?php if(!$isPublic): ?><?php if($errors!==[]): ?><div class="alert alert-error"><?php foreach($errors as $error): ?><p><?= $escape($error) ?></p><?php endforeach; ?></div><?php endif; ?><form class="game-form goal-form" method="post" action="/?<?= $escape(http_build_query(['route'=>'franchise','name'=>$franchise['name']])) ?>"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="franchise" value="<?= $escape($franchise['name']) ?>"><label><span>Goal</span><input name="goal_title" maxlength="120" required placeholder="Own every mainline game"></label><div class="form-row"><label><span>Count</span><select name="goal_type"><option value="all">All items</option><option value="games">Games</option><option value="merchandise">Merchandise</option></select></label><label><span>Target</span><input type="number" name="target_count" min="1" max="10000" value="10" required></label></div><button class="primary-button">Add collection quest</button></form><?php endif; ?></section></aside></main></body></html>
