<?php

declare(strict_types=1);

/** Renders the authenticated franchise atlas index. */

$escape=static fn(string $value): string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');$themeStyle="--accent:{$currentUser->themeAccent()};--bg:{$currentUser->themeBackground()};--panel:{$currentUser->themePanel()};--text:{$currentUser->themeText()};";
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Franchise Atlas — ArchiveXP</title><link rel="stylesheet" href="/assets/app.css"></head><body class="theme-<?= $escape($currentUser->themePreset()) ?> density-<?= $escape($currentUser->layoutDensity()) ?> <?= $currentUser->franchiseImage()!==null?'has-dashboard-image image-mode-'.$escape($currentUser->franchiseImageMode()):'' ?>" style="<?= $escape($themeStyle) ?><?= $currentUser->franchiseImage()!==null?'--dashboard-image:url(\'/?route=franchise-image\');--dashboard-overlay:'.($currentUser->franchiseOverlay()/100):'' ?>">
<header class="site-header atlas-header"><div><p class="eyebrow">Connected collection</p><h1>Franchise Atlas</h1><p class="lede">See how games, characters, platforms, and physical collectibles connect.</p></div><div class="summary"><strong><?= count($franchises) ?></strong><span>franchises</span></div></header>
<div class="account-bar"><div class="account-identity"><?php if($currentUser->profileImage()!==null): ?><img class="account-avatar account-avatar-image" src="/?route=profile-image&amp;user=<?= rawurlencode($currentUser->username()??'') ?>" alt=""><?php else: ?><span class="account-avatar"><?= $escape(strtoupper(substr($currentUser->displayName(),0,1))) ?></span><?php endif; ?><span><small>Signed in as</small><strong><?= $escape($currentUser->displayName()) ?></strong></span></div><a class="account-button" href="/?route=account">My Account</a><a class="account-button" href="/?route=appearance">Appearance</a><a class="account-button" href="/?route=profile-settings">Public profile</a><form method="post" action="/?route=logout"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><button class="logout-button">Sign out</button></form></div>
<nav class="section-switcher"><a href="/">Home</a><a href="/?route=games">Games</a><a href="/?route=merchandise">Merchandise</a><a class="is-active" href="/?route=franchises">Franchises</a></nav>
<form class="atlas-search" method="get"><input type="hidden" name="route" value="franchises"><input type="search" name="q" value="<?= $escape($search) ?>" placeholder="Search franchises…"><button class="filter-button">Search</button><?php if($search!==''): ?><a class="reset-link" href="/?route=franchises">Reset</a><?php endif; ?></form>
<main class="atlas-grid"><?php foreach($franchises as $franchise): ?><a class="atlas-card" href="/?<?= $escape(http_build_query(['route'=>'franchise','name'=>$franchise['name']])) ?>"><div><p class="eyebrow">Franchise</p><h2><?= $escape($franchise['name']) ?></h2></div><div class="atlas-card-stats"><span><strong><?= count($franchise['games']) ?></strong> games</span><span><strong><?= count($franchise['merchandise']) ?></strong> collectibles</span><span><strong><?= count($franchise['characters']) ?></strong> characters</span></div><div class="progress-heading"><span>Games completed</span><strong><?= count($franchise['games'])===0?0:(int)floor($franchise['completed']/count($franchise['games'])*100) ?>%</strong></div><div class="progress-track"><span style="width:<?= count($franchise['games'])===0?0:(int)floor($franchise['completed']/count($franchise['games'])*100) ?>%"></span></div><span class="atlas-open">Explore collection →</span></a><?php endforeach; ?><?php if($franchises===[]): ?><section class="panel empty-state"><span>◇</span><h2>No franchises found</h2><p>Add a franchise in Collection details for a game or directly on a merchandise record.</p></section><?php endif; ?></main></body></html>
