<?php

declare(strict_types=1);

/** Renders a collector's privacy-safe, shareable Display Cabinet. */

$escape=static fn(string $value): string=>htmlspecialchars($value,ENT_QUOTES,'UTF-8');
if (!isset($user) || $user===null): ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cabinet unavailable — ArchiveXP</title><link rel="stylesheet" href="/assets/app.css"></head><body><main class="public-empty"><p class="eyebrow">ArchiveXP</p><h1>Cabinet unavailable</h1><p>This profile is private or does not exist.</p><a class="account-button" href="/">Open ArchiveXP</a></main></body></html><?php return; endif;
$themeStyle="--accent:{$user->themeAccent()};--bg:{$user->themeBackground()};--panel:{$user->themePanel()};--text:{$user->themeText()}";
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $escape($user->profileDisplayName()) ?>'s Cabinet — ArchiveXP</title><meta name="description" content="<?= $escape($user->profileBio()!==''?$user->profileBio():'Explore this ArchiveXP collection.') ?>"><meta property="og:title" content="<?= $escape($user->profileDisplayName()) ?>'s ArchiveXP Cabinet"><meta property="og:description" content="<?= $escape($user->profileBio()) ?>"><link rel="stylesheet" href="/assets/app.css"></head>
<body class="public-cabinet theme-<?= $escape($user->themePreset()) ?> density-<?= $escape($user->layoutDensity()) ?>" style="<?= $escape($themeStyle) ?>">
<header class="public-profile-header"><?php if($user->profileImage()!==null): ?><img class="public-profile-photo" src="/?route=profile-image&user=<?= rawurlencode($user->username() ?? '') ?>" alt="<?= $escape($user->profileDisplayName()) ?> profile photograph"><?php else: ?><span class="public-profile-photo profile-photo-placeholder"><?= $escape(strtoupper(substr($user->profileDisplayName(),0,1))) ?></span><?php endif; ?><div><p class="eyebrow">ArchiveXP Display Cabinet</p><h1><?= $escape($user->profileDisplayName()) ?></h1><?php if($user->profileBio()!==''): ?><p class="lede"><?= $escape($user->profileBio()) ?></p><?php endif; ?></div><a class="account-button" href="/">Create your cabinet</a></header>
<section class="public-stats"><article><strong><?= count($games) ?></strong><span>Games</span></article><article><strong><?= $completed ?></strong><span>Completed</span></article><article><strong><?= count($merchandise) ?></strong><span>Collectibles</span></article></section>
<nav class="public-cabinet-nav"><span>Explore this collection by franchise from the franchise name shown on each connected item.</span></nav>
<form class="public-filter" method="get"><input type="hidden" name="route" value="display-cabinet"><input type="hidden" name="user" value="<?= $escape($user->username() ?? '') ?>"><input type="search" name="q" value="<?= $escape($search) ?>" placeholder="Search this cabinet…"><select name="section"><option value="all">Everything</option><option value="games" <?= $section==='games'?'selected':'' ?>>Games</option><option value="merchandise" <?= $section==='merchandise'?'selected':'' ?>>Merchandise</option></select><button class="filter-button">Search</button></form>
<main class="public-collection"><?php if($section!=='merchandise'): ?><section><div class="panel-heading"><div><p class="eyebrow">Games</p><h2>Game collection</h2></div><span><?= count($games) ?> shown</span></div><div class="public-card-grid"><?php foreach($games as $game): ?><article class="public-item-card"><span class="status-pill"><?= $escape($game->collectionType()->value) ?></span><h3><?= $escape($game->title()) ?></h3><p><?= $escape($game->platform()) ?></p><div class="progress-heading"><span>Progress</span><strong><?= $game->progress() ?>%</strong></div><div class="progress-track"><span style="width:<?= $game->progress() ?>%"></span></div></article><?php endforeach; ?><?php if($games===[]): ?><p class="empty-state">No games match this search.</p><?php endif; ?></div></section><?php endif; ?>
<?php if($section!=='games'): ?><section><div class="panel-heading"><div><p class="eyebrow">Merchandise</p><h2>Physical collection</h2></div><span><?= count($merchandise) ?> shown</span></div><div class="public-card-grid"><?php foreach($merchandise as $item): ?><article class="public-item-card"><span class="status-pill"><?= $escape($item->collectionType()->value) ?></span><h3><?= $escape($item->name()) ?></h3><p><?= $escape($item->franchise()) ?></p><div class="public-item-meta"><span><?= $escape($item->category()->label()) ?></span><span><?= $escape($item->packaging()->label()) ?></span><span>×<?= $item->quantity() ?></span></div></article><?php endforeach; ?><?php if($merchandise===[]): ?><p class="empty-state">No merchandise matches this search.</p><?php endif; ?></div></section><?php endif; ?></main><footer class="public-footer">Shared with ArchiveXP · Private ownership data is hidden</footer></body></html>
